'use client';

import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import {
  EXAM_BY_SLUG,
  type ExamSlug,
  type NexipediaArticleSummary,
} from '@nexigrate/shared';
import { Logo } from '~/components/Logo';
import { useAuth } from '~/lib/auth-context';
import { api, type MeResponse } from '~/lib/api';

/**
 * /guides -- Phase 17 student page for exam-prep how-to articles.
 *
 * Surfaces the dedicated 'exam-guide' Nexipedia category. Same 3-AI
 * pipeline, same admin review, same reader as Nexipedia. The student
 * just sees an exam-prep-styled landing instead of the encyclopedia
 * browse, and the listing groups by relevant exam.
 *
 * Reader URL is the existing /nexipedia/<slug>; the article header
 * shows the 'Exam guide' category pill so the context is clear.
 */
export default function GuidesPage() {
  const { user, loading } = useAuth();
  const router = useRouter();

  const [me, setMe] = useState<MeResponse['user'] | null>(null);
  const [articles, setArticles] = useState<NexipediaArticleSummary[] | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [examFilter, setExamFilter] = useState<ExamSlug | 'all'>('all');

  useEffect(() => {
    if (!loading && !user) router.replace('/signin');
  }, [user, loading, router]);

  useEffect(() => {
    if (!user) return;
    let cancelled = false;
    (async () => {
      try {
        const [meRes, listRes] = await Promise.all([
          api.me(),
          api.nexipedia.list({ category: 'exam-guide', limit: 100 }),
        ]);
        if (cancelled) return;
        setMe(meRes.user);
        setArticles(listRes.articles);
      } catch (e) {
        if (!cancelled) {
          setError(e instanceof Error ? e.message : 'failed to load guides');
        }
      }
    })();
    return () => {
      cancelled = true;
    };
  }, [user]);

  // Default to the student's target exam if it's in the article set.
  useEffect(() => {
    if (!me?.targetExam || !articles || examFilter !== 'all') return;
    const targetSlug = me.targetExam;
    const hasTargetExam = articles.some((a) => a.relatedExams.includes(targetSlug));
    if (hasTargetExam) setExamFilter(targetSlug);
  }, [me, articles, examFilter]);

  const examsWithGuides = useMemo(() => {
    if (!articles) return [] as ExamSlug[];
    const set = new Set<ExamSlug>();
    for (const a of articles) for (const e of a.relatedExams) set.add(e);
    return Array.from(set).sort((a, b) => {
      const an = EXAM_BY_SLUG.get(a)?.name ?? a;
      const bn = EXAM_BY_SLUG.get(b)?.name ?? b;
      return an.localeCompare(bn);
    });
  }, [articles]);

  const visible = useMemo(() => {
    if (!articles) return [] as NexipediaArticleSummary[];
    if (examFilter === 'all') {
      return articles
        .slice()
        .sort((a, b) => (a.title < b.title ? -1 : 1));
    }
    return articles
      .filter((a) => a.relatedExams.includes(examFilter))
      .sort((a, b) => (a.title < b.title ? -1 : 1));
  }, [articles, examFilter]);

  if (loading || !user) {
    return (
      <main className="flex min-h-[60vh] items-center justify-center px-6">
        <span className="inline-flex items-center gap-2 text-sm text-muted-500">
          <span className="spinner" aria-hidden="true" />
          Loading...
        </span>
      </main>
    );
  }

  return (
    <main className="mx-auto flex min-h-screen max-w-3xl flex-col px-6 pt-8 pb-16">
      <header className="flex items-start justify-between">
        <Logo />
        <div className="flex items-center gap-2">
          <Link href="/dashboard" className="btn-ghost-sm">
            Dashboard
          </Link>
          <Link href="/learn" className="btn-ghost-sm">
            Learning tips
          </Link>
        </div>
      </header>

      <section className="mt-10">
        <p className="pill mb-3">Exam guides</p>
        <h1 className="font-serif text-3xl font-semibold leading-tight text-ink-900 sm:text-4xl">
          How to crack your exam, without the noise.
        </h1>
        <p className="mt-2 text-ink-800">
          Practical, exam-authority-cited preparation guides. Generated by
          three AIs, fact-checked against the official syllabus and pattern,
          then editor-approved. No coaching ads, no YouTube hype.
        </p>
      </section>

      {examsWithGuides.length > 0 ? (
        <section className="mt-6 flex flex-wrap gap-2">
          <FilterPill
            active={examFilter === 'all'}
            label="All exams"
            onClick={() => setExamFilter('all')}
          />
          {examsWithGuides.map((e) => (
            <FilterPill
              key={e}
              active={examFilter === e}
              label={EXAM_BY_SLUG.get(e)?.name ?? e}
              onClick={() => setExamFilter(e)}
            />
          ))}
        </section>
      ) : null}

      {error ? (
        <div className="banner banner-error mt-6" role="alert">
          <span>{error}</span>
        </div>
      ) : null}

      {!articles && !error ? (
        <p className="mt-8 text-sm text-muted-500">Loading guides...</p>
      ) : null}

      {articles && visible.length === 0 ? (
        <section className="paper-card mt-8 p-6 sm:p-8">
          <p className="text-xs font-semibold uppercase tracking-[0.18em] text-muted-500">
            {examFilter === 'all' ? 'Coming soon' : 'No guides for that exam yet'}
          </p>
          <h2 className="font-serif mt-2 text-xl font-semibold text-ink-900">
            {examFilter === 'all'
              ? 'No guides published yet'
              : 'Try a different exam'}
          </h2>
          <p className="mt-2 text-ink-800">
            {examFilter === 'all'
              ? "Our editors are seeding the first batch of exam guides. Check back soon."
              : 'Pick another exam from the filter or come back later.'}
          </p>
          <div className="mt-4 flex gap-2">
            {examFilter !== 'all' ? (
              <button
                type="button"
                onClick={() => setExamFilter('all')}
                className="btn-ghost"
              >
                Show all exams
              </button>
            ) : null}
            <Link href="/learn" className="btn-ghost">
              Learning tips
            </Link>
          </div>
        </section>
      ) : null}

      {visible.length > 0 ? (
        <section className="mt-8 grid gap-3 sm:grid-cols-2">
          {visible.map((a) => (
            <Link
              key={a.id}
              href={`/nexipedia/${encodeURIComponent(a.slug)}`}
              className="paper-card block h-full p-5 transition hover:bg-paper-200/40"
            >
              <p className="text-xs font-semibold uppercase tracking-[0.14em] text-ember-600">
                {a.relatedExams.length > 0
                  ? a.relatedExams
                      .map((e) => EXAM_BY_SLUG.get(e)?.name ?? e)
                      .join(' · ')
                  : 'General'}
              </p>
              <h3 className="font-serif mt-2 text-lg font-semibold leading-snug text-ink-900">
                {a.title}
              </h3>
              <p className="mt-2 line-clamp-2 text-sm text-ink-800">{a.summary}</p>
              <p className="mt-3 text-xs text-muted-500">
                {a.estimatedReadMinutes} min read · verified by 3 AIs
              </p>
            </Link>
          ))}
        </section>
      ) : null}
    </main>
  );
}

function FilterPill({
  active,
  label,
  onClick,
}: {
  active: boolean;
  label: string;
  onClick: () => void;
}) {
  return (
    <button
      type="button"
      onClick={onClick}
      aria-pressed={active}
      className={
        'rounded-full border px-3 py-1 text-xs font-medium transition ' +
        (active
          ? 'border-ink-900 bg-ink-900 text-paper-100'
          : 'border-line bg-paper-50 text-ink-800 hover:border-ember-500')
      }
    >
      {label}
    </button>
  );
}
