import type { ExamSlug, ISODateTime } from './brand.js';

/**
 * Nexipedia -- "Wikipedia for Indian students" (Phase 14).
 *
 * Topic-scoped, NOT exam-scoped: an article on "Photosynthesis" or "Indian
 * Constitution" lives once and is useful to NEET, CBSE, UPSC, and SSC
 * aspirants alike. Generated by the same 3-AI pipeline as MCQs and
 * chapters; published only after admin approval.
 *
 * Editorial differences from a chapter:
 *   - Encyclopedia voice (third-person, no exam framing).
 *   - Categories instead of exams (science, history, civics, ...).
 *   - Optional `relatedExams` array so a student browsing from JEE Main
 *     can see "Physics constants relevant to your exam".
 *   - Verifier rubric emphasises factual accuracy over coverage; an
 *     article that's narrow but verifiably true is preferred to a broad
 *     one with shaky claims.
 *
 * Lifecycle:
 *   1. Admin POSTs (slug, title, category, optional outline) ->
 *      /v1/admin/nexipedia/generate
 *   2. Generator emits a JSON article with title, summary, sections[]
 *   3. Two verifiers score factual accuracy + structure + clarity
 *   4. Draft lands in `nexipedia_drafts/{id}` with status='pending'
 *   5. Admin reviews, optionally edits wording, approves
 *   6. On approve, copied into `nexipedia_articles/{id}` with isPublished=true
 *
 * The same id is reused on approve so re-approval is idempotent.
 */

/** Branded id for a Nexipedia article (also used for its draft). */
export type NexipediaArticleId = string & { readonly __brand: 'NexipediaArticleId' };

export const asNexipediaArticleId = (s: string): NexipediaArticleId =>
  s as NexipediaArticleId;

/**
 * Top-level categories. Stable, append-only -- adding a new category is
 * fine, renaming is a breaking change. Mirrors the structure used by
 * Indian secondary-school + competitive-exam syllabi.
 */
export const NEXIPEDIA_CATEGORIES = [
  'science',
  'mathematics',
  'history',
  'geography',
  'civics-polity',
  'economy',
  'literature',
  'biography',
  'current-affairs',
  'general-knowledge',
  // Phase 17 additions: re-use the same 3-AI pipeline + admin review for
  // exam-prep how-to content and study-technique articles. Editorially
  // distinct (see prompts.ts CATEGORY_HINTS) but lifecycle is identical.
  'exam-guide',
  'learning-tip',
] as const;

export type NexipediaCategory = (typeof NEXIPEDIA_CATEGORIES)[number];

export const NEXIPEDIA_CATEGORY_LABELS: Record<NexipediaCategory, string> = {
  science: 'Science',
  mathematics: 'Mathematics',
  history: 'History',
  geography: 'Geography',
  'civics-polity': 'Civics & Polity',
  economy: 'Economy',
  literature: 'Literature',
  biography: 'Biographies',
  'current-affairs': 'Current affairs',
  'general-knowledge': 'General knowledge',
  'exam-guide': 'Exam guide',
  'learning-tip': 'Learning tip',
};

export type NexipediaArticleStatus = 'pending' | 'approved' | 'rejected';

export interface NexipediaSection {
  id: string;
  heading: string;
  /** Markdown body. **bold**, $inline math$, $$display math$$. NO HTML. */
  body: string;
  order: number;
}

export interface NexipediaVerifierScore {
  modelId: string;
  /** Factual accuracy: 0 = multiple errors, 1 = verified against official. */
  factualAccuracy: number;
  /** Structure: 0 = disorganised, 1 = encyclopedia-grade. */
  structure: number;
  /** Pedagogical clarity for a school student: 0 = confusing, 1 = clear. */
  clarity: number;
  agreesAccurate: boolean;
  reasoning: string;
  factualErrors: string[];
  passedAt: ISODateTime;
}

/** A published Nexipedia article shown to students. */
export interface NexipediaArticle {
  id: NexipediaArticleId;
  /** Stable kebab-case slug, e.g. 'photosynthesis' or 'partition-of-india'. */
  slug: string;
  title: string;
  /** 1-2 sentence summary used in cards and search results. */
  summary: string;
  category: NexipediaCategory;
  /**
   * Optional list of exams this article is most relevant to. Used to surface
   * "Articles for your exam" on the dashboard. Empty array means general
   * knowledge that applies to everyone.
   */
  relatedExams: ExamSlug[];
  sections: NexipediaSection[];
  estimatedReadMinutes: number;
  /** Free-form citation, e.g. 'NCERT Class 12 Biology, Ch. 13'. */
  source: string;
  /**
   * Lowercased keyword tokens for substring search. Generated server-side
   * from title + summary + category so search doesn't need a full-text
   * index for the small initial corpus.
   */
  searchTokens: string[];
  generatedBy: string;
  verifiers: NexipediaVerifierScore[];
  /** Combined verification score in [0, 1]. */
  verificationScore: number;
  smeApprovedBy: string | null;
  smeApprovedAt: ISODateTime | null;
  isPublished: boolean;
  createdAt: ISODateTime;
  updatedAt: ISODateTime;
}

/** A generated draft awaiting admin approval. */
export interface NexipediaArticleDraft {
  id: NexipediaArticleId;
  slug: string;
  title: string;
  summary: string;
  category: NexipediaCategory;
  relatedExams: ExamSlug[];
  sections: NexipediaSection[];
  estimatedReadMinutes: number;
  source: string;
  generatedBy: string;
  verifiers: NexipediaVerifierScore[];
  verificationScore: number;
  status: NexipediaArticleStatus;
  reviewedBy: string | null;
  reviewedAt: ISODateTime | null;
  rejectionReason: string | null;
  createdAt: ISODateTime;
  updatedAt: ISODateTime;
}

/**
 * Slim summary returned by the public list endpoint. No section bodies, so
 * the search/browse page stays lightweight.
 */
export interface NexipediaArticleSummary {
  id: NexipediaArticleId;
  slug: string;
  title: string;
  summary: string;
  category: NexipediaCategory;
  relatedExams: ExamSlug[];
  estimatedReadMinutes: number;
  source: string;
  sectionCount: number;
}
